### ISSUE TITLE
[BUG] check_file_is_complete always fails for MEF images

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/mirar#469]
**Describe the bug**
When using the current check_file_is_complete function for all MEF images, it always fails. I don't think I fully understand the logic of this function.

**Expected behaviour**
It will not fail and say that the MEF image is complete

**Comment by virajkaram** [comment]
Fixing by setting it to astropy logic (sets file incomplete if file.tell() > file.size())

**Comment by virajkaram** [comment]
https://github.com/astropy/astropy/blob/1ef68aa829db94b1c506afbb7f6fc2faeaf4eee5/astropy/io/fits/file.py#L430

**Comment by robertdstein** [comment]
The fix implemented in #475 :

https://github.com/winter-telescope/mirar/blob/5e68b3242117566ac84427787bc01b4179e80cc1/mirar/io.py#L240

does not work. It always returns true. As a consequence, the monitor is completely broken, because it tries to read in images which are partially written to disk. We need to reverse this, in a way that mef images pass.
